### ISSUE TITLE
App: Ideris

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-ideris#1]
- [x] Setup do repo (falta o token de parceiro);
- [x] Configuração do app seguindo instruções em [next steps](https://github.com/ecomplus/app-ideris#next-steps);
- [x] Rota para envio de produtos da E-Com Plus -> Ideris;
- Tratar [webhooks](https://github.com/ecomplus/app-ideris#webhook) da E-Com Plus (a partir de procedures configurados) para criar/atualizar pedidos da plataforma no Ideris (**API do Ideris não suporta POST em pedidos** :-1: );
- [x] Tratar [webhooks](https://github.com/ecomplus/app-ideris#webhook) da E-Com Plus para atualizar estoque/preços de produtos no Ideris;
- [x] Receber/ler atualizações de estoque na Ideris e repassar para a E-Com Plus:
  > Pelo que vi na referência da API a implementação que me veio à cabeça por enquanto foi consumir ativamente toda a lista de produtos em intervalos, mas não me parece uma boa ideia porque teria um delay na sincronização e muito mais requisições do que o necessário, também pensei em ficar lendo o resource `Status`, mas não necessariamente o status do produto (ou de um pedido) seria alterado, o lojista poderia alterar o estoque do produto de outra forma, certo?
Há alguma forma de cadastrar webhooks? Se não, há algum resource da API que me entregue uma fila de alterações ou logs da loja?
- [x] Descrição e um ícone legal (@vitorrgg ) pro Market (instruções [aqui](https://github.com/ecomplus/app-ideris#optional-setup-for-market));

**Comment by leomp12** [comment]
@vitorrgg arruma o ícone e descrição pro app aqui por favor

**Comment by vitorrgg** [comment]
![ideris](https://user-images.githubusercontent.com/35348281/94467832-ddef3e80-0199-11eb-88ae-89b0ec4b9f73.png)
O Ideris é um hub integrador de marketplaces. Com esse app você pode sincronizar estoques de sua loja virtual com os anúncios ativos nos mais diversos marketplaces.

**Comment by leomp12** [comment]
https://github.com/ecomplus/app-ideris/commit/e805da28da2263df9841dd51e56b0f42d552be48
